backend:
  name: git-gateway
  repo: arthurfontainecom-wq/Fiche-de-securite-Supbiotech
  branch: main

# Ce dossier sert de secours, mais ne sera pas utilisé par les collections en dessous
media_folder: "pdf"
public_folder: "/pdf"

collections:
  - name: "fiches_villejuif"
    label: "Fiches Villejuif"
    folder: "pdf/villejuif"
    create: true
    # ICI LE RÉGLAGE MAGIQUE :
    media_folder: "" 
    public_folder: ""
    fields:
      - { label: "Nom du produit", name: "title", widget: "string" }
      - { label: "Fichier PDF", name: "file", widget: "file" }

  - name: "fiches_lyon"
    label: "Fiches Lyon"
    folder: "pdf/lyon"
    create: true
    # PAREIL ICI :
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Nom du produit", name: "title", widget: "string" }
      - { label: "Fichier PDF", name: "file", widget: "file" }
