backend:
  name: git-gateway
  repo: arthurfontainecom-wq/Fiche-de-securite-Supbiotech
  branch: main

collections:
  - name: "fiches_villejuif"
    label: "Fiches Villejuif"
    folder: "pdf/villejuif"
    media_folder: "" 
    public_folder: ""
    create: true
    fields:
      - { label: "Nom du produit", name: "title", widget: "string" }
      - { label: "Fichier PDF", name: "file", widget: "file" }

  - name: "fiches_lyon"
    label: "Fiches Lyon"
    folder: "pdf/lyon"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { label: "Nom du produit", name: "title", widget: "string" }
      - { label: "Fichier PDF", name: "file", widget: "file" }
